services:
  - type: web
    name: portfolio-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DOPPLER_TOKEN
        sync: false
    autoDeploy: true

databases:
  - name: portfolio-tracker-db
    databaseName: portfolio_tracker
    ipAllowList: []  # Allow all IPs 