services:
  - type: web
    name: portfolio-tracker
    env: python
    plan: free
    buildCommand: |
      curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
      doppler setup --no-interactive
      pip install --no-cache-dir -r requirements.txt
    startCommand: doppler run -- python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DOPPLER_TOKEN
        sync: false
      - key: DOPPLER_PROJECT
        value: portfolio-tracker
      - key: DOPPLER_CONFIG
        value: prd
    autoDeploy: true

databases:
  - name: portfolio-tracker-db
    databaseName: portfolio_tracker
    ipAllowList: []  # Allow all IPs 